#! /bin/bash

PATH_TO_CERTS=''
PATH_TO_CREDS=''

# Check for server call of maintenance
# if maintenance mode exit

python invalidate.py

# Remove certificates and credentials
rm -rf "$PATH_TO_CERTS"
rm -rf "$PATH_TO_CREDS"
